INSERT INTO agents (
  id,
  name,
  occupation,
  persona_summary,
  current_location_id,
  state,
  current_activity,
  is_npc,
  is_active,
  letta_agent_id,
  letta_message_endpoint,
  home_location_id
)
VALUES
  (
    'eddy_lin',
    'Eddy Lin',
    'Music Student',
    'Practices obsessively and keeps a late-night schedule.',
    'lin_bedroom',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_eddy_lin',
    NULL,
    'lin_bedroom'
  ),
  (
    'isabella_rodriguez',
    'Isabella Rodriguez',
    'Cafe Owner',
    'Runs Hobbs Cafe and thrives in social interactions.',
    'hobbs_cafe_counter',
    'working',
    'Serving coffee',
    TRUE,
    TRUE,
    'placeholder_isabella_rodriguez',
    NULL,
    'hobbs_cafe_seating'
  ),
  (
    'klaus_mueller',
    'Klaus Mueller',
    'Mayor',
    'Methodical and caffeinated. Now serves as the town mayor, managing civic affairs.',
    'townhall_mayor_office',
    'working',
    'Working at the mayor''s desk',
    TRUE,
    TRUE,
    'placeholder_klaus_mueller',
    NULL,
    'townhall_mayor_office'
  ),
  (
    'maria_lopez',
    'Maria Lopez',
    'Artist',
    'Paints around town with an erratic schedule.',
    'ville_park_west',
    'working',
    'Sketching park fountain',
    TRUE,
    TRUE,
    'placeholder_maria_lopez',
    NULL,
    'ville_park_west'
  ),
  (
    'sam_moore',
    'Sam Moore',
    'Shop Assistant',
    'Punctual and practical, helps at Harvey Oak Supermart.',
    'harvey_oak_aisle',
    'working',
    'Organizing shop shelves',
    TRUE,
    TRUE,
    'placeholder_sam_moore',
    NULL,
    'harvey_oak_aisle'
  ),
  (
    'rosie_kim',
    'Rosie Kim',
    'Shopkeeper',
    'Owns Harvey Oak Supermart. Warm but shrewd. Keeps the shelves stocked and the books balanced.',
    'harvey_oak_checkout',
    'working',
    'Minding the checkout',
    TRUE,
    TRUE,
    'placeholder_rosie_kim',
    NULL,
    'harvey_oak_checkout'
  ),
  (
    'abigail_chen',
    'Abigail Chen',
    'Student',
    'Friendly student who spends time between college and cafe.',
    'oak_classroom_a',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_abigail_chen',
    NULL,
    'oak_classroom_a'
  ),
  (
    'city_treasury',
    'City Treasury',
    'City Treasury',
    'Municipal fund that pays civic employees and maintains public services.',
    'notice_board',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_city_treasury',
    NULL,
    'notice_board'
  ),
  (
    'bank_treasury',
    'Bank Treasury',
    'Bank Treasury',
    'Ledger entity for Smallville Bank capital, reserves, and bank payroll.',
    'smallville_bank_vault',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_bank_treasury',
    NULL,
    'smallville_bank_vault'
  ),
  (
    'nora_patel',
    'Nora Patel',
    'Banker',
    'Runs Smallville Bank with a careful eye on rates, reserves, and who needs credit.',
    'smallville_bank_office',
    'working',
    'Reviewing the town bank ledger',
    TRUE,
    TRUE,
    'placeholder_nora_patel',
    NULL,
    'smallville_bank_office'
  )
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    occupation = EXCLUDED.occupation,
    persona_summary = EXCLUDED.persona_summary,
    current_location_id = EXCLUDED.current_location_id,
    state = EXCLUDED.state,
    current_activity = EXCLUDED.current_activity,
    is_npc = EXCLUDED.is_npc,
    is_active = EXCLUDED.is_active,
    letta_agent_id = EXCLUDED.letta_agent_id,
    letta_message_endpoint = EXCLUDED.letta_message_endpoint,
    home_location_id = EXCLUDED.home_location_id,
    updated_at = NOW();