INSERT INTO agents (
  id,
  name,
  occupation,
  persona_summary,
  current_location_id,
  state,
  current_activity,
  is_npc,
  is_active,
  letta_agent_id,
  letta_message_endpoint,
  home_location_id
)
VALUES
  (
    'eddy_lin',
    'Eddy Lin',
    'Music Student',
    'Practices obsessively and keeps a late-night schedule.',
    'lin_bedroom',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_eddy_lin',
    NULL,
    'lin_bedroom'
  ),
  (
    'isabella_rodriguez',
    'Isabella Rodriguez',
    'Cafe Owner',
    'Runs Hobbs Cafe and thrives in social interactions.',
    'hobbs_cafe_counter',
    'working',
    'Serving coffee',
    TRUE,
    TRUE,
    'placeholder_isabella_rodriguez',
    NULL,
    'hobbs_cafe_seating'
  ),
  (
    'klaus_mueller',
    'Klaus Mueller',
    'Professor',
    'Methodical and caffeinated, teaches long sessions.',
    'oak_staff_office',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_klaus_mueller',
    NULL,
    'oak_staff_office'
  ),
  (
    'maria_lopez',
    'Maria Lopez',
    'Artist',
    'Paints around town with an erratic schedule.',
    'ville_park_west',
    'working',
    'Sketching park fountain',
    TRUE,
    TRUE,
    'placeholder_maria_lopez',
    NULL,
    'ville_park_west'
  ),
  (
    'sam_moore',
    'Sam Moore',
    'Shop Assistant',
    'Punctual and practical, helps at Harvey Oak Supply.',
    'harvey_oak_floor',
    'working',
    'Organizing shop shelves',
    TRUE,
    TRUE,
    'placeholder_sam_moore',
    NULL,
    'harvey_oak_floor'
  ),
  (
    'abigail_chen',
    'Abigail Chen',
    'Student',
    'Friendly student who spends time between college and cafe.',
    'oak_classroom_a',
    'idle',
    NULL,
    TRUE,
    TRUE,
    'placeholder_abigail_chen',
    NULL,
    'oak_classroom_a'
  )
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    occupation = EXCLUDED.occupation,
    persona_summary = EXCLUDED.persona_summary,
    current_location_id = EXCLUDED.current_location_id,
    state = EXCLUDED.state,
    current_activity = EXCLUDED.current_activity,
    is_npc = EXCLUDED.is_npc,
    is_active = EXCLUDED.is_active,
    letta_agent_id = EXCLUDED.letta_agent_id,
    letta_message_endpoint = EXCLUDED.letta_message_endpoint,
    home_location_id = EXCLUDED.home_location_id,
    updated_at = NOW();